### ISSUE TITLE
dict.pop() should return a union type when parameter `default` is specified

### ISSUE THREAD

**Issue by rkr-at-dbx** [python/typeshed#614] opened 2016-10-17 16:33 UTC
Something along the lines of

```
@overload
def pop(self, k: _KT) -> _VT: ...
@overload
def pop(self, k: _KT, default: _T = ...) -> Union[_T, _VT]: ...
```

**Comment by gvanrossum** [comment] 2016-10-17 18:15
Thanks, this is a duplicate of #278.

**Closed by gvanrossum** 2016-10-17 18:15 UTC
