### ISSUE TITLE
asyncio definitions wrong

### ISSUE THREAD

**Issue by brianmay** [python/typeshed#1447] opened 2017-07-01 04:02 UTC
Hello,

A number of definitions around asyncio appear to be wrong. For reference I have included code excerpts and messages from mypy.

For example, ``create_datagram_endpoint`` and ``sendto`` both take address parameters. These are defined as `str`, but the correct type I believe is `Tuple[str, int]` as it includes the port number too.

```
self._loop.create_datagram_endpoint(
            lifx_discovery,
            local_addr=('0.0.0.0', UDP_BROADCAST_PORT),
)
self._transport.sendto(msg.generate_packed_message(), (UDP_BROADCAST_IP, UDP_BROADCAST_PORT)
```

gives:

```
aiolifxc/aiolifx.py:195: error: Argument 2 to "create_datagram_endpoint" of "AbstractEventLoop" has incompatible type "Tuple[str, int]"; expected "str"
aiolifxc/aiolifx.py:1264: error: Argument 2 to "sendto" of "DatagramTransport" has incompatible type "Tuple[str, int]"; expected "str"
```

I am also having problems with:

``loop.create_task`` - won't accept a `Coroutine`, expects `Union[Future[<nothing>], Generator[Any, None, <nothing>]]`.

```
class XYZ:
    async def _fire_sending(self, msg: Message, num_repeats: int) -> None:
        ...

    def other_function():
       ...
       self._loop.create_task(self._fire_sending(msg, num_repeats))
```

Gives:

```
aiolifxc/aiolifx.py:531: error: Argument 1 to "create_task" of "AbstractEventLoop" has incompatible type Awaitable[None]; expected "Union[Future[<nothing>], Generator[Any, None, <nothing>]]"
```

(I am somewhat confused why it says this is an `Awaitable` type, I expected it should be a `Coroutine` type..)

``loop.add_reader`` and ``loop_remove_reader - won't accept `TextIO`, expects `int`.

```
loop.add_reader(sys.stdin, read_in_wrapper)
loop.remove_reader(sys.stdin)
```
gives:

```
examples/lifx-cli.py:214: error: Argument 1 to "add_reader" of "AbstractEventLoop" has incompatible type "TextIO"; expected "int"
examples/lifx-cli.py:225: error: Argument 1 to "remove_reader" of "AbstractEventLoop" has incompatible type "TextIO"; expected "int"
```

There are are also some issues I am less certain off - might reflect actual problems or my lack of understanding:

* Shouldn't it be possible to return the result of ``create_datagram_endpoint()`` into an `Awaitable` or a `Coroutine` or a `Future`? I get errors if I try to do so.

* Protocol handlers based on ``DatagramProtocol`` have a ``connection_made()`` function that receives a ``BaseTransport`` parameter that - shouldn't this be a ``DatagramTransport`` type?

I can provide extra information as required.

**Comment by JelleZijlstra** [comment] 2017-07-01 17:39
Thanks for the detailed reports! I'm putting together a PR to fix these now. Detailed notes:
- Confirmed that `create_datagram_endpoint` and `sendto` need a `Tuple[str, int]`, not a `str`
- `create_task` was already fixed in #1272 
- I'm not sure what `add_reader` and `remove_reader` are supposed to accept. https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.add_reader says they need a file descriptor, not an IO object. On the other hand, the example at https://docs.python.org/3/library/asyncio-eventloop.html#asyncio-watch-read-event passes a socket to `add_reader`. It seems like the fd is passed into the `selectors` module, and the type to be used there was discussed in #482, so I think I'll just use `selectors._FileObject` in the asyncio stub.

I'm not sure about your last two questions—could you provide code that demonstrates the problems you mention?

**Comment by brianmay** [comment] 2017-07-01 23:04
Thanks. For the last two points:

```
    def get_discover_coro(
            self, ipv6prefix: str=None,
            discovery_interval: int=DISCOVERY_INTERVAL,
            discovery_step: int=DISCOVERY_STEP) -> Awaitable:

        def lifx_discovery() -> aio.BaseProtocol:
            """ Construct an LIFX discovery protocol handler. """
            return LifxDiscovery(
                loop=self._loop,
                devices=self,
                ipv6prefix=ipv6prefix,
                discovery_interval=discovery_interval,
                discovery_step=discovery_step,
            )

        return self._loop.create_datagram_endpoint(
            lifx_discovery,
            local_addr=('0.0.0.0', UDP_BROADCAST_PORT),
        )

...

    coro = devices.get_discover_coro()
    server = loop.create_task(coro)  # type: aio.Task
```

Gives exactly the same errors I described before. Oh wait. I was getting another error before. Where did it go... Ok, skip this one. Next...

A protocol handler is implemented like:

```
class LifxDiscovery(aio.DatagramProtocol):

    def connection_made(self, transport: aio.BaseTransport) -> None:
        transport.sendto(...)   # fails, as sendto is not part of BaseTrasnport
        assert(transport, aio.DatagramTransport)  # fails, because an internal unrelated object class is used
        datagram_transport = cast(aio.DatagramTransport, transport)
        datagram_transport.sendto(...)   # this works
```

I find the documentation is vague, however I believe the intention is that you are suppose to treat
``transport`` as if it is a `DatagramTransport` here.

Thanks

**Comment by brianmay** [comment] 2017-07-01 23:07
In the ``get_discover_coro()`` example above, I am not sure what the return type for ``get_discover_coro`` should be... This seems to work - that doesn't mean it is ideal. Any suggestions appreciated.

**Comment by brianmay** [comment] 2017-07-01 23:43
Also for reference, full source code is available: https://github.com/brianmay/aiolifxc

**Comment by JelleZijlstra** [comment] 2017-07-02 22:28
I think `get_discover_coro` should return something like `Awaitable[Tuple[Transport, Protocol]]`. Just `Awaitable` is equivalent to `Awaitable[Any]`, which is imprecise and should generally be avoided.

As for your `connection_made` example, my understanding is that `BaseProtocol`'s `connection_made` method takes a `BaseTransport` object. In `DatagramProtocol`, a subclass of `BaseProtocol`, `connection_made` instead receives a `DatagramTransport`. I'm not sure that's something that the type system can express easily, since subclass methods generally need to accept argument types at least as broad as those that their parent class expects. We could perhaps support it with something like this (untested):
```
T = TypeVar('T', bound=BaseTransport)

class BaseProtocol(Generic[T]):
    def connection_made(self, transport: T) -> None: ...

class DatagramProtocol(BaseProtocol[DatagramTransport]):
    def connection_made(self, transport: DatagramTransport) -> None: ...
```
But if you're actually using an unrelated class in your own code, then this solution doesn't seem ideal either.

**Comment by lambdalisue** [comment] 2017-07-03 16:47
It seems `*args: List[Any]` in `add_reader` and `add_writer` are wrong as well.

The following code gives me `Argument 3 to "add_writer" of "AbstractEventLoop" has incompatible type "socket"; expected List[Any]` in Python 3.6

```python
# _send := Callback
# sock := socket.socket
loop.add_writer(sock.fileno(), _send, sock, bytes(icmp), writer, loop)
```

```
src/asyncping/core.py|47 error| Argument 3 to "add_writer" of "AbstractEventLoop" has incompatible type "socket"; expected List[Any]
src/asyncping/core.py|47 error| Argument 4 to "add_writer" of "AbstractEventLoop" has incompatible type "bytes"; expected List[Any]
src/asyncping/core.py|47 error| Argument 5 to "add_writer" of "AbstractEventLoop" has incompatible type Future[int]; expected List[Any]
src/asyncping/core.py|47 error| Argument 6 to "add_writer" of "AbstractEventLoop" has incompatible type "AbstractEventLoop"; expected List[Any]
src/asyncping/core.py|52 error| Argument 3 to "add_reader" of "AbstractEventLoop" has incompatible type "socket"; expected List[Any]
src/asyncping/core.py|52 error| Argument 4 to "add_reader" of "AbstractEventLoop" has incompatible type Future[int]; expected List[Any]
src/asyncping/core.py|52 error| Argument 5 to "add_reader" of "AbstractEventLoop" has incompatible type "AbstractEventLoop"; expected List[Any]
```

**Comment by JelleZijlstra** [comment] 2017-07-03 16:48
Yes, that should be `*args: Any`. I'll add it to my open PR.

**Comment by brianmay** [comment] 2017-07-03 22:12
@JelleZijlstra: Yes, I thought fixing ``connection_made`` might be problematic. Personally, your solution looks fine to me (assuming it works :-) ).

**Closed** 2017-07-06 21:22 UTC
