### ISSUE TITLE
Question: behavior of stub files as packages evolve

### ISSUE THREAD

**Issue by snakescott** [python/typeshed#711] opened 2016-11-24 20:05 UTC
It doesn't look like stubs in ```third_party``` are versioned with the packages they represent. E.g. there is ```third_party/2/boto```, not  ```third_party/2/boto/v2.42.0```, ```third_party/2/boto/v2.43.0```, ....  

As boto adds (or worse, changes or removes!) functionality and APIs, my dependent codebase -- and requires/install_requires dependencies -- will evolve with it in ways that seem potentially more complex than what picking a typeshed.git revision to power mypy supports. 

In this case do I need to be managing my own typeshed? Are there best practices for ensuring consistency between a codebase (including dependencies) and a typeshed?

**Comment by gvanrossum** [comment] 2016-11-24 20:51
This is a duplicate of #153.

**Closed by gvanrossum** 2016-11-24 20:51 UTC

**Comment by snakescott** [comment] 2016-11-24 20:56
Thanks! I'll try to make sure to search existing issues next time.
