### ISSUE TITLE
stdlib: Use protocols instead of `IO` for `GZipFile`

### ISSUE THREAD

**Issue by jlost** [python/typeshed#5163] opened 2021-03-31 14:51 UTC
Kicking this problem upstream: https://github.com/python/typeshed/issues/5099

> GzipFile is still using IO as argument type, which is discouraged. We prefer custom protocols for argument types, and that would hopefully fix the problem above. 

Does it make sense to use custom protocols in `GZipFile`? Would it be an improvement?

**Comment by JelleZijlstra** [comment] 2021-03-31 14:55
Yes, this is the direction we want in general. You don't necessarily need custom protocols; it's possible that something like `_typeshed.SupportsWrite` will suffice (I haven't checked).

**Comment by srittau** [comment] 2021-04-01 05:17
What Jelle said. Please ignore the word "custom" in my quote above. That said, this is just a duplicate of #5099.

**Closed by srittau** 2021-04-01 05:17 UTC
