### ISSUE TITLE
No overload variant of "get" … for os.environ with unicode_literals

### ISSUE THREAD

**Issue by posita** [python/typeshed#1274] opened 2017-05-18 04:39 UTC
This works:

```py
# test.py
import os
print('PWD: {}'.format(os.environ.get('PWD', '<not set>')))
```

```
$ python --version
Python 2.7.13
$ python test.py
PWD: …
$ python3 --version
Python 3.6.0
$ python3 test.py
PWD: …
$ mypy test.py
$ mypy --py2 test.py
```

This fails validation with `--py2`:

```py
# test_unicode_literals.py
from __future__ import unicode_literals  # this is new
import os
print('PWD: {}'.format(os.environ.get('PWD', '<not set>')))
```

```
$ python test_unicode_literals.py
PWD: …
$ python3 test_unicode_literals.py
PWD: …
$ mypy test_unicode_literals.py
$ mypy --py2 test_unicode_literals.py
test_unicode_literals.py:3: error: No overload variant of "get" of "Mapping" matches argument types [builtins.unicode, builtins.unicode]
```

See [`stdlib/2/os/__init__.pyi`#L67](https://github.com/python/typeshed/blob/b03e79886e22d4b0a258e93ab1445743107d391d/stdlib/2/os/__init__.pyi#L67).

**Comment by posita** [comment] 2017-05-18 04:47
This seems to address the issue for Python 2:

```py
# test_unicode_literals_workaound.py
from __future__ import unicode_literals
import os
import typing
class _Environ(typing.MutableMapping[typing.AnyStr, typing.AnyStr], typing.Generic[typing.AnyStr]): pass
environ = typing.cast(_Environ[typing.Union[str, unicode]], os.environ)
print('PWD: {}'.format(environ.get('PWD', '<not set>')))
```

```
$ mypy --py2 test_unicode_literals_workaound.py
```

**Comment by JelleZijlstra** [comment] 2017-07-01 18:46
I'm not sure this is fixable in typeshed. python/mypy#3619 might provide a suitable workaround.

**Comment by JelleZijlstra** [comment] 2018-04-05 00:04
Duplicate of #872.

**Closed by JelleZijlstra** 2018-04-05 00:04 UTC
