### ISSUE TITLE
types-protobuf 3.14.19 broken

### ISSUE THREAD

**Issue by ziima** [python/typeshed#7519] opened 2022-03-21 07:56 UTC
Since the release of `types-protobuf` 3.14.19, the type checking based on this package produces a number of errors such as
```
Library stubs not installed for "google.protobuf.empty_pb2" (or incompatible with Python 3.9)
```

### MVE ###
```python
#/tmp/test_protobuf.py 
from google.protobuf.empty_pb2 import Empty

e = Empty()
```
```sh
python3 -m venv test-protobuf-venv
source test-protobuf-venv/bin/activate
pip install mypy types-protobuf
mypy /tmp/test_protobuf.py
```
The script fails with types-protobuf 3.14.19, but works with 3.14.18, regardless of python version (errors observed for 3.7 to 3.10).

**Comment by hauntsaninja** [comment] 2022-03-21 08:05
I believe this should be fixed with `--namespace-packages` (or `namespace_packages = True`). This will be the default for mypy soon.

**Comment by ziima** [comment] 2022-03-21 08:08
@hauntsaninja That applies to `types-protobuf` itself or to its usage?

**Comment by ziima** [comment] 2022-03-21 08:14
Found it.
```sh
mypy --namespace-packages /tmp/test_protobuf.py
```
works fine. That's probably the issue.

**Comment by heroesm** [comment] 2022-03-21 08:21
Reproduce in Python3.7 and types-protobuf==3.19.14
```
python3 -m pip install -U types-protobuf

Requirement already satisfied: types-protobuf in ... (3.18.3)
Collecting types-protobuf
  Downloading types_protobuf-3.19.14-py3-none-any.whl (52 kB)
     |████████████████████████████████| 52 kB 103 kB/s
Installing collected packages: types-protobuf
  Attempting uninstall: types-protobuf
    Found existing installation: types-protobuf 3.18.3
    Uninstalling types-protobuf-3.18.3:
      Successfully uninstalled types-protobuf-3.18.3                                     
Successfully installed types-protobuf-3.19.14

if type mypy ; then \                                                                                                                                                                         
        mypy --install-types --non-interactive ... || mypy ... ; \
fi                                                                                                                                                                                            
mypy is /home/users/.../.pyenv/shims/mypy  
Installing missing stub packages:                                                                                                                                                             
/home/users/.../.pyenv/versions/3.7.5/envs/py37env/bin/python3.7 -m pip install types-protobuf

Requirement already satisfied: types-protobuf in /home/users/.../.pyenv/versions/3.7.5/envs/py37env/lib/python3.7/site-packages (3.19.14)
WARNING: You are using pip version 21.3.1; however, version 22.0.4 is available.
You should consider upgrading via the '/home/users/.../.pyenv/versions/3.7.5/envs/py37env/bin/python3.7 -m pip install --upgrade pip' command.

nscan/plugin.py:10: error: Library stubs not installed for "google.protobuf.message" (or incompatible with Python 3.7)
nscan/plugin.py:10: note: Hint: "python3 -m pip install types-protobuf"
nscan/plugin.py:10: note: (or run "mypy --install-types" to install all missing stub packages)
nscan/plugin.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 905 source files)
nscan/plugin.py:10: error: Library stubs not installed for "google.protobuf.message" (or incompatible with Python 3.7)
nscan/plugin.py:10: note: Hint: "python3 -m pip install types-protobuf"
nscan/plugin.py:10: note: (or run "mypy --install-types" to install all missing stub packages)
nscan/plugin.py:10: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 905 source files)

```

But after downgrade types-protobuf==3.19.13 the issue disappears.

Run mypy with `--namespace-packages` also works

**Comment by srittau** [comment] 2022-03-21 15:55
Reopening to allow discussion of reverting this.

**Comment by gurelkaynak** [comment] 2022-03-21 17:10
This is definitely a breaking change IMO. I regularly update minor versions and this is totally unexpected. A minor version update shouldn't make me add flags and change other flags and so on. 

Here's what happened: 
The minor version update broke our pipeline in an MR. I had to enable namespace_packages but then it started to include some other files that were excluded before because of the follow_imports thing. Then I spent the whole day to try to figure out these things and finally fixed it by enabling namespace_packages and changing follow_imports to "silent". 

The documentation doesn't state that even if I excluded some folders it can be included by a follow_imports functionality (or I couldn't find anything about this).

**Comment by nipunn1313** [comment] 2022-03-21 18:28
Hi, author of #6106 here.

@JelleZijlstra / @srittau Please revert it. Thanks.

Clearly, `--namespace-packages` as a default (https://github.com/python/mypy/pull/9636) is very important.
Furthermore, I believe #6106 would require a major version bump, not a minor one - to avoid breaking from underneath people.

Thanks everyone for jumping on the reports so quickly.

**Closed** 2022-03-21 18:49 UTC

**Comment by AlexWaygood** [comment] 2022-03-21 18:55
The breaking change has been reverted.
