### ISSUE TITLE
Support concatenation between lists of different types

### ISSUE THREAD

**Issue by ktbarrett** [python/typeshed#5756] opened 2021-07-10 16:40 UTC
In Python adding a list of strings and a list of ints results in a list of strings and ints, but currently this is not supported by typing.

```python
a = list[int]()
b = list[str]()
reveal_type(a + b)  # error: Unsupported operand types for + ("List[int]" and "List[str]")
```

Instead, we could provide an overload such that the result of the operation becomes `List[Union[int, str]]`.
This also has the nice effect where `Union[str, str_subtype]` can be reduced to `str`, so it works to implement automatic promotion as well.

**Comment by JelleZijlstra** [comment] 2021-07-10 17:21
See https://github.com/python/typeshed/pulls?q=is%3Apr++list+__add__+ for previous attempts in this area. There doesn't seem to be an issue about it yet though.

**Comment by Akuli** [comment] 2021-07-10 17:37
When working with programs that use `subprocess.call`, this is the most annoying thing about typing in Python to me. But as you can hopefully see by the previous attempts here and in mypy, trying to fix this tends to break things in weird ways.

**Comment by ktbarrett** [comment] 2021-07-10 18:09
Just to be clear, the issue is with mypy's treatment of list and tuple literals where it isn't using typeshed's definition of `list.__add__` and `tuple.__add__` when handling literal expressions? For the fix to be made here, a similar and simultaneous fix to mypy would have to occur?

**Comment by JelleZijlstra** [comment] 2021-07-10 18:17
I'm not sure anyone figured out exactly what's going on.

**Comment by JelleZijlstra** [comment] 2022-01-31 05:55
Duplicate of #2383

**Closed by JelleZijlstra** 2022-01-31 05:55 UTC
