### ISSUE TITLE
Confusion on return type of difflib.get_closest_matches

### ISSUE THREAD

**Issue by deveshks** [python/typeshed#3906] opened 2020-04-04 20:09 UTC
There is a mismatch between the return type mentioned in the docs of [difflib.get_close_matches](https://docs.python.org/3/library/difflib.html#difflib.get_close_matches) (`List[str]`) vs what is mentioned in typeshed [source code](https://github.com/python/typeshed/blob/master/stdlib/2and3/difflib.pyi#L42) (`List[Sequence[_T]]`)

This was observed when I was trying to add type annotations to https://github.com/pypa/pip/blob/master/src/pip/_internal/commands/__init__.py#L103

**Comment by McSinyx** [comment] 2020-04-05 04:24
As you mentioned in the linked PR, this is a duplicate of GH-2067.  Generally it's not a good idea to re-file an issue.

**Comment by deveshks** [comment] 2020-04-05 04:34
Hi @McSinyx 

I had a discussion with @pradyunsg and he mentioned that https://github.com/python/typeshed/issues/2067 is in fact not a different bug, hence I have filed this bug.

**Comment by pradyunsg** [comment] 2020-04-05 04:39
s/not a different/definitely a different/

**Comment by JelleZijlstra** [comment] 2020-04-05 04:49
This does sound like the same issue as #2067. As I said there, it's fixable with an overload, and I just submitted #3908 doing that.

Here's the relevant behavior:
```
In [10]: difflib.get_close_matches('x', ['y', 'zx'])                                                                                                                                              
Out[10]: ['zx']

In [11]: difflib.get_close_matches((1, 2, 3), [(1, 2), (1, 2, 3, 4)])                                                                                                                             
Out[11]: [(1, 2, 3, 4), (1, 2)]
```

**Comment by deveshks** [comment] 2020-04-05 08:53
Thanks @JelleZijlstra for the quickaround and the fix. Really appreciate it 😄

**Closed** 2020-04-05 12:12 UTC
