### ISSUE TITLE
calling .register on typing.KeysView subclass causes false positive error `Member "register" is unknown`

### ISSUE THREAD

**Issue by jab** [python/typeshed#9296] opened 2022-11-29 00:44 UTC
Type checkers that include the recent changes from ~~https://github.com/python/typeshed/pull/8977~~ https://github.com/python/typeshed/pull/9058 (e.g. pyright v1.1.281) now incorrectly emit an error like `Member "register" is unknown` for the following line of code:

https://github.com/jab/bidict/blob/522c9b69249d66c201fed608f95a5da8d3064ed8/bidict/_base.py#L51

Type checkers that do not include those changes (e.g. pyright v1.1.278) do not emit any error for that line, as expected.

Copy/pasted excerpt:
```python
import typing as t

from ._typing import KT  # a typevar


class BidictKeysView(t.KeysView[KT], t.ValuesView[KT]):
    """Since the keys of a bidict are the values of its inverse (and vice versa),
    the :class:`~collections.abc.ValuesView` result of calling *bi.values()*
    is also a :class:`~collections.abc.KeysView` of *bi.inverse*.
    """


dict_keys: t.Type[t.KeysView[t.Any]] = type({}.keys())
BidictKeysView.register(dict_keys)  # <-- false positive error emitted here
```

Please let me know if there is any other info I can provide. Thank you!

**Comment by JelleZijlstra** [comment] 2022-11-29 01:35
I don't think the typeshed change you link to is relevant. Probably #9058 is the culprit instead.

**Comment by hauntsaninja** [comment] 2022-11-29 02:09
It's relevant in that #9058 wouldn't have happened if not for #8977.

Also, #8977 was mostly done for aesthetic reasons, so if we need to fix in typeshed, I suggest we roll back #8977 (as per option 2 in https://github.com/python/typeshed/pull/8977#issuecomment-1297872394)

Of course, in the medium term we should also fix the mypy bug this exposed https://github.com/python/typeshed/pull/9058#issuecomment-1299972677 / https://github.com/python/mypy/issues/13986 (maybe it's already fixed?). The reason CI didn't complain is because this needs https://github.com/python/mypy/pull/13579 to break, which was not part of a released mypy at the time.

I'm assuming @jab ran into this in the context of bidict. We do have bidict in mypy_primer and didn't see any regressions, so maybe this is something mypy has some special casing for?

**Comment by AlexWaygood** [comment] 2022-11-30 15:50
> Also, #8977 was mostly done for aesthetic reasons, so if we need a short-term fix in typeshed, I suggest we roll back #8977 (as per option 2 in [#8977 (comment)](https://github.com/python/typeshed/pull/8977#issuecomment-1297872394))

Agreed that rolling back #8977 and #9058 seems like a good option for now.

**Comment by jab** [comment] 2022-12-10 17:33
Thanks @JelleZijlstra, @hauntsaninja, and @AlexWaygood for looking this.

> Agreed that rolling back https://github.com/python/typeshed/pull/8977 and https://github.com/python/typeshed/pull/9058 seems like a good option for now.

I'm new to this codebase, but submitted #9348 with these reversions, along with a regression test. Hope this helps.

> I'm assuming @jab ran into this in the context of bidict.

Yes.

> We do have bidict in mypy_primer

TIL, cool and thank you!

> and didn't see any regressions, so maybe this is something mypy has some special casing for?

Do you know, @JelleZijlstra?

> There's a chance this might be the very first time we've had an issue where a pyright_primer would be useful

FWIW, I believe this is [not the very first](https://github.com/microsoft/pyright/issues/3534 ([and maybe not even the second](https://github.com/microsoft/pyright/issues/3183)) time.

Looks like there's already a dedicated issue for considering a pyright_primer (https://github.com/python/typeshed/issues/7642), maybe now the time is right?

Thanks again for working together on this.

**Comment by JelleZijlstra** [comment] 2022-12-10 18:17
> > and didn't see any regressions, so maybe this is something mypy has some special casing for?
> 
> Do you know, @JelleZijlstra?

I haven't looked but this feels like an area where typecheckers need to hardcode a lot of behavior, since Protocol classes and ABCs are special in ways that are core of the type system. It's not surprising that different type checkers handle this case differently.

Closing as #9348 was merged.

**Closed by JelleZijlstra** 2022-12-10 18:17 UTC
