### ISSUE TITLE
Add license file to PyPI releases of types-decorator

### ISSUE THREAD

**Issue by bkmgit** [python/typeshed#12930] opened 2024-10-31 02:31 UTC
Would be helpful if the [license file](https://github.com/python/typeshed/blob/main/LICENSE) is also packaged.

**Comment by AlexWaygood** [comment] 2024-10-31 08:18
Thanks, we agree this is something we'd like. Closing as a duplicate of https://github.com/typeshed-internal/stub_uploader/issues/89

**Closed by AlexWaygood** 2024-10-31 08:18 UTC
