### ISSUE TITLE
Consider defining standard decorator for generic types that are not runtime subscriptable

### ISSUE THREAD

**Issue by erictraut** [python/typeshed#4515] opened 2020-09-07 18:00 UTC
Some classes defined as generic in the builtins typeshed stubs have implementations that do not allow for runtime subscripting. If a type annotation attempts to provide type arguments, a type checker will allow it, but a runtime exception will occur. Examples include the following:

```python
from queue import Queue
from collections import OrderedDict
from asyncio import Future

a: Queue[int] = Queue()
b: OrderedDict[str, str] = OrderedDict()
c: Future[int] = Future()
```

The workaround is to specify these annotations as string literals:
```
a: "Queue[int]" = Queue()
b: "OrderedDict[str, str]" = OrderedDict()
c: "Future[int]" = Future()
```

It would be really helpful if a type checker could detect this situation and save the user from the surprise at runtime, but there's currently no way for a type checker to know which classes are not runtime subscriptable. Has there been any discussion of how to address this?

Here are a few proposals to consider:

*Proposal 1: Class decorator*
Define a class decorator "@runtime_subscript_disallowed" (or something similar) that can be used only in type stubs. It would be used like this:

```python
@runtime_subscript_disallowed
class Queue(Generic[_T]):
    ...
```

*Proposal 2: Function decorator for `__init__`*
Similar to proposal 1, but rather than being used on the class, the decorator would be applied to the `__init__` method for that class. This makes it easier to conditionalize based on Python versions:

```python
class Queue(Generic[_T]):
   if sys.version_info < (3, 10):
      @runtime_subscript_disallowed
      def __init__(self, maxsize: int = ...) -> None: ...
   else:
      def __init__(self, maxsize: int = ...) -> None: ...
    ...
```

*Proposal 3: Special form of Generic*
Introduce a variant of `Generic` called `GenericNoRuntime` (or something similar). This would be valid only in type stubs and would be used to define classes that are generic from the perspective of the type checker but are not subscriptable at runtime. This proposal has the downside that all type checkers would need to be revved to understand this new special type.

```python
class Queue(GenericNoRuntime[_T]):
    ...
```

Of these three, I have a slight preference for proposal 2.

Thoughts? Other suggestions?

**Comment by hauntsaninja** [comment] 2020-09-07 21:02
Note that queue.Queue (and all the others in stdlib) are generic at runtime from 3.9 on, not 3.10 on. Given PEP 585 and 563, I think this becomes a very niche problem, so would be opposed to invasive solutions like Proposal 3.

For what it's worth, mypy took the approach of hardcoding these:
https://github.com/python/mypy/blob/master/mypy/typeanal.py#L59 (clearly a very incomplete list, but I guess empirically good enough)
https://github.com/python/mypy/blob/master/mypy/nodes.py#L108 (suggest the equivalent from typing. also seems very incomplete, but maybe I'm missing something)
I think there's a better list out there somewhere as part of implementing PEP 585. But given that 98% of the problem is in ~20 classes which will mostly go away on its own (through use of future import, 3.9 and 3.10) and mitigated by the fact that Generics already have discoverability issues, maybe this doesn't need a standardised solution in stubs.

One potential nit with Proposal 2 is I think there are generic classes that only have `__new__` (iirc, subprocess.Popen). But overall, a decorator approach seems fine to me.

**Comment by hauntsaninja** [comment] 2020-10-17 21:36
I was looking at this for mypy, and here's a simple idea: what if we just use the presence of `__class_getitem__` to determine this?
Here's the tracking issue for doing this well in typeshed: #4682

**Comment by hauntsaninja** [comment] 2020-10-17 21:59
One possible solution here: assume all Generics in the standard library are not runtime subscriptable unless they've defined `__class_getitem__` (see #4682 for making sure typeshed has good coverage of that). This should work as long as a) typeshed doesn't define `__class_getitem__` on Generic, which we currently do not, b) CPython doesn't introduce code inheriting from Generic and typeshed forgets to put a `__class_getitem__` on it, c) you don't care too much about supporting this in third party stubs.

**Comment by erictraut** [comment] 2020-10-18 05:58
I ended up hardcoding these in pyright, similar to mypy's approach. Your proposal has merit, but since this problem has already been largely solved and will eventually go away as older versions of the language "age out", it's probably not worth it at this point.

**Comment by hauntsaninja** [comment] 2020-10-18 06:10
Sounds good, I'll close this issue out then :-)

**Closed by hauntsaninja** 2020-10-18 06:10 UTC
