### ISSUE TITLE
unittest.mock fails because of subclassing Any

### ISSUE THREAD

**Issue by q0w** [python/typeshed#7503] opened 2022-03-17 08:05 UTC
After https://github.com/python/typeshed/pull/6379 mypy fails with ``disallow_subclassing_any = True``
```sh
error: Class cannot subclass "Any" (has type "Any")
```

**Comment by AlexWaygood** [comment] 2022-03-17 08:07
Hmm, perhaps we should run mypy with that config option in CI.

**Comment by JelleZijlstra** [comment] 2022-03-17 17:20
@q0w can you be more specific than "mypy fails"? What are you running mypy on exactly?

mypy generally suppresses errors in typeshed when running on user code.

**Comment by itaisteinherz** [comment] 2022-03-18 12:03
When running `mypy_test` locally with `--disallow-subclassing-any` set, I also get this error:

```
stdlib/unittest/mock.pyi:119: error: Class cannot subclass "Any" (has type "Any")  [misc]
```

https://github.com/python/typeshed/blob/e8286e7048aeeced78c24d6d38bf49e5b92ddf88/stdlib/unittest/mock.pyi#L119

**Comment by AlexWaygood** [comment] 2022-03-18 12:12
> When running `mypy_test` locally with `--disallow-subclassing-any` set, I also get this error:
> 
> ```
> stdlib/unittest/mock.pyi:119: error: Class cannot subclass "Any" (has type "Any")  [misc]
> ```
> 
> https://github.com/python/typeshed/blob/e8286e7048aeeced78c24d6d38bf49e5b92ddf88/stdlib/unittest/mock.pyi#L119

Sure, but does anybody get this error when running mypy on code outside of this repo? If not, it doesn't really matter. (I haven't yet tried to reproduce it.)

**Comment by q0w** [comment] 2022-03-18 12:38
@JelleZijlstra @AlexWaygood when I've run pytest with https://github.com/typeddjango/pytest-mypy-plugins
https://github.com/dry-python/returns/runs/5581765222?check_suite_focus=true

**Comment by AlexWaygood** [comment] 2022-06-12 13:36
Mypy should suppress any errors in typeshed. If it doesn't, that's a mypy issue, not a typeshed issue. If the pytest plugin in question is using mypy programmatically, then that's also not a typeshed issue -- it's a mypy issue if they're doing documented things, and it's an issue with the pytest plugin if they're reaching into mypy internals in a way that they shouldn't be.

It looks like the specific issue with the pytest plugin has since been fixed in https://github.com/dry-python/returns/pull/1385, anyhow.

**Closed by AlexWaygood** 2022-06-12 13:36 UTC
