### ISSUE TITLE
Pattern method types look wrong in Python 2

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#2199] opened 2018-06-05 17:39 UTC
Looking at the definition of Pattern in stdlib/2/typing.pyi, I have a feeling that the types of the methods are incorrect. In Python 2, the types of the methods are unrelated to the type of the regex with which the pattern was instantiated. The current definition seems to prohibit e.g.
```py
# ...imports...
pat = re.compile(r'[a-z]+')  # Line 11
reveal_type(pat)
reveal_type(pat.sub(u'zzz', u'abc'))
```
Gives
```
_.py:11: error: Revealed type is 'typing.Pattern[builtins.str*]'
_.py:12: error: Revealed type is 'Any'
_.py:12: error: No overload variant of "sub" of "Pattern" matches argument types "unicode", "unicode"
```
But at runtime this works fine -- if I replace `reveal_type` with `print` it prints
```
<_sre.SRE_Pattern object at 0x100689d50>
u'zzz'
```

**Comment by JelleZijlstra** [comment] 2018-06-12 05:39
Duplicate of #1892.

**Closed by JelleZijlstra** 2018-06-12 05:39 UTC
