### ISSUE TITLE
"StreamWriter" has no attribute "wait_closed"

### ISSUE THREAD

**Issue by gleb-chipiga** [python/typeshed#2844] opened 2019-03-10 09:42 UTC
Code:
```
reader, writer = await asyncio.open_connection(host, port)
...
self._writer.close()
await self._writer.wait_closed()
```

mypy 0.670 gives an error:
```
error: "StreamWriter" has no attribute "wait_closed"
```

**Comment by srittau** [comment] 2019-03-10 11:47
Duplicate of #2313. Patches welcome!

**Closed by srittau** 2019-03-10 11:47 UTC
