### ISSUE TITLE
Inconsistency in Optional check depending on unrelated variables in __init__

### ISSUE THREAD

**Issue by ShadowTemplate** [python/typeshed#2591] opened 2018-11-08 12:29 UTC
Hi! I'm a new mypy user and I hope this issue is not related to my inexperience. I've noticed some inconsistencies related to Optional. 
The following example does not produce any error with mypy 0.641 and mypy-extensions 0.4.1:
```python
from typing import List, Optional, Union

class A:
    def __init__(self, foo):
        self.my_list: List[Optional[Union[A]]] = 2 * [None]
```
But as soon as I specify the type for the argument _foo_, things change:
```python
from typing import List, Optional, Union

class A:
    def __init__(self, foo: int):
        self.my_list: List[Optional[Union[A]]] = 2 * [None]
```
> error: Incompatible types in assignment (expression has type "List[None]", variable has type "List[Optional[A]]")

The attribute _my_list_ isn't related to _foo_, so I can't see why the output should change.
Thanks a lot for your attention.

**Comment by srittau** [comment] 2018-11-08 13:11
The problem is that in the first example mypy `__init__()` is not type checked, since it is not annotated. Two solutions are to run mypy with `--check-untyped-defs` or to annotate `__init__()`, at least partially.

I think the reason that mypy complains about this assignment is that it infers `2 * [None]` to be of type `List[None]`, which is indeed incompatible with `List[Optional[Union[A]]]`, due to the invariance of lists. I believe mypy could be smarter in this case, by recognizing that the right side of the assignment is only used in this location (and writing `[None, None]` actually works). It's possible that there is already a mypy issue open about this.

**Comment by ilevkivskyi** [comment] 2018-11-08 14:59
There is a similar issue about list concatenation (which is going to be closed by a recent typeshed change to `__add__`). I am not sure we can do something without special-casing in mypy, so it is probably not worth it. You can still open issue on mypy tracker if you want.

**Closed by ilevkivskyi** 2018-11-08 14:59 UTC

**Comment by ShadowTemplate** [comment] 2018-11-08 15:44
Oh, I see! Thanks a lot for your help and your work.
Have a nice day!
