### ISSUE TITLE
unittest.mock.patch decorator doesn't accept args

### ISSUE THREAD

**Issue by ashb** [python/typeshed#3270] opened 2019-09-27 10:40 UTC
Airflow uses mypy and the latest update (0.730) started causing us errors, that I think are related to invalid typing on mock.patch.

```python
from unittest import mock

...

    @mock.patch(
        'airflow.gcp.hooks.base.GoogleCloudBaseHook.project_id',
        new_callable=PropertyMock,
        return_value=GCP_PROJECT_ID_HOOK_UNIT_TEST
    )
```

(from https://github.com/apache/airflow/blob/2abf0f5b70970bcd16e8cf5846ba67cf3945ecae/tests/gcp/hooks/test_cloud_build.py#L118-L122)

Causes these errors:

```
tests/gcp/operators/test_cloud_build.py:118: error: Argument 2 to "__call__" of "_patcher" has incompatible type "**Dict[str, Dict[str, object]]"; expected "bool"

tests/gcp/operators/test_cloud_build.py:134: error: Argument 2 to "__call__" of "_patcher" has incompatible type "**Dict[str, Dict[str, object]]"; expected "bool"

tests/gcp/operators/test_cloud_build.py:171: error: Argument 2 to "__call__" of "_patcher" has incompatible type "**Dict[str, Dict[str, object]]"; expected "bool"
```

(There are more examples of the same error in https://travis-ci.org/apache/airflow/jobs/590239664)

I'm not sure if this is a bug in the type definition or a bug in mypy itself.

**Comment by srittau** [comment] 2019-09-27 11:22
I am not sure what is going on, but I can't reproduce it with this simple test case:

```python
from unittest import mock
from unittest.mock import PropertyMock

@mock.patch(
    'airflow.gcp.hooks.base.GoogleCloudBaseHook.project_id',
    new_callable=PropertyMock,
    return_value=''
)   
@mock.patch("airflow.gcp.hooks.cloud_build.CloudBuildHook.get_conn")
@mock.patch("airflow.gcp.hooks.cloud_build.time.sleep")
def test_error_operation(self, _, get_conn_mock, mock_project_id):
    pass
```

**Comment by ashb** [comment] 2019-09-27 11:34
Iiinteresting.

If I run `mypy tests/gcp/operators/test_cloud_build.py` it doesn't error, but it does if I run `mypy tests/` -- that is probably pointing more towards a bug in mypy than a typeshed error.

**Comment by ashb** [comment] 2019-09-27 11:37
Here's a minimal repro case at least:

```python
import unittest
from unittest import mock

class TestCloudBuildHookWithPassedProjectId(unittest.TestCase):
    @mock.patch(
        'airflow.gcp.hooks.base.GoogleCloudBaseHook.project_id',
        new_callable=mock.PropertyMock,
        **{"return_value.classify_text.return_value": {}}
    )
    def test_error_operation(self, _, mock_project_id):
        pass
```

Oddly that seems to "leak" in to other files.

**Comment by srittau** [comment] 2019-09-27 12:18
Filed as python/mypy#7572, where I have a repro that doesn't use typeshed stubs. Closing here.

**Closed by srittau** 2019-09-27 12:18 UTC
