### ISSUE TITLE
matching bytes regular expression against unicode

### ISSUE THREAD

**Issue by matthiaskramm** [python/typeshed#1133] opened 2017-04-03 22:42 UTC
The following is valid Python 2:

```
re.compile(b"foo").match(u"foo")
```

Should typeshed allow this? Right now, https://github.com/python/typeshed/blob/master/stdlib/2/re.pyi defines compile as:
```
def compile(pattern: AnyStr, flags: int = ...) -> Pattern[AnyStr]: ...
```

And `match()`, in `Pattern`, is defined in https://github.com/python/typeshed/blob/master/stdlib/2/typing.pyi#L350 as:

```
class Pattern(Generic[AnyStr]):
  def match(self, string: AnyStr) -> Match[AnyStr]: ...
```

This disallows mixing bytes/unicode. Is this what we want?

Matching a bytes regexp against unicode is a `TypeError` in Python 3, so there's a case for not supporting this; however we do have some cases on our side were this is flagged as a type error in valid Python 2 code.

**Comment by gvanrossum** [comment] 2017-04-22 00:57
I'm okay with supporting this for PY2.

**Comment by JelleZijlstra** [comment] 2017-04-23 01:19
This is a duplicate of #273.

**Closed by JelleZijlstra** 2017-04-23 01:19 UTC
Labels: question
