### ISSUE TITLE
classmethod and staticmethod have no __call__

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#1684] opened 2017-10-24 13:04 UTC
Adding a simple ``__call__`` like this:
```python
class classmethod(Generic[T]):
    def __init__(self, func: T) -> None:
    __call__: T
```
will reduce number of false positives for some dynamic code that calls it directly ``foo = classmethod(foo)``.

**Comment by JelleZijlstra** [comment] 2018-10-20 05:56
When somebody submits a PR :).

**Comment by srittau** [comment] 2018-10-21 13:28
Closing as dupe of #870.

**Closed by srittau** 2018-10-21 13:28 UTC
Labels: size-small
