### ISSUE TITLE
`pkgutil.get_loader` appears to not be flexible enough

### ISSUE THREAD

**Issue by rbcasperson** [python/typeshed#3177] opened 2019-08-08 22:29 UTC
```
$ python --version
Python 3.7.0
$ mypy --version
mypy 0.720
```

I have some code in an `__init__.py` file that looks like this:

```py
import os
import pkgutil


loader = pkgutil.get_loader(__package__)
for pkg in pkgutil.walk_packages([os.path.dirname(loader.get_filename())]):
    ...
```

This code executes exactly how I expect it to, but `mypy` is giving me this error:
```
.../__init__.py:5: error: "Loader" has no attribute "get_filename"
```

Looking at [this line](https://github.com/python/typeshed/blob/de1755b263ed0b80aba35f043550c91a508c3d08/stdlib/2and3/pkgutil.pyi#L7), it appears that typeshed expects the `loader` variable in my code to have the type `importlib.abc.Loader` in any python3 version. However, when I inspect my code, I see that the `loader` variable is an instance of `_frozen_importlib_external.SourceFileLoader`, which does indeed have the `get_filename` attribute.

Looking [here](https://docs.python.org/3/library/pkgutil.html?highlight=get_loader#pkgutil.get_loader) and [here](https://docs.python.org/3/glossary.html#term-loader) in the Python 3.7 documentation, it appears that `importlib.abc.Loader` should be correct.

I'm not sure exactly what would be causing the difference in return type.

I did find this closed issue: https://github.com/python/typeshed/issues/2793 that provides me a solution to make `mypy` happy:

```py
from _frozen_importlib_external import SourceFileLoader


loader = pkgutil.get_loader(__package__)
assert isinstance(loader, SourceFileLoader)
```

I also tried setting the type as `importlib.machinery.SourceFileLoader` which seemed better since that doesn't import from a private package, but `mypy` shows some new errors:

```
error: Too few arguments for "get_filename" of "FileLoader"
```

In any case, I have my workaround for now, but it still seems like this should be considered an issue in typeshed.

I'll be happy to investigate more and see if there's any rhyme or reason to when `get_loader` will return different kinds of types, but I wanted to start the conversation here at least.

**Comment by srittau** [comment] 2019-10-11 07:08
The problem is that `get_loader()` can return different kinds of loaders, depending on where the package is located:

```
>>> import pkgutil
>>> pkgutil.get_loader("os")
<_frozen_importlib_external.SourceFileLoader object at 0x7f88d775f6d8>
>>> pkgutil.get_loader("sys")
<class '_frozen_importlib.BuiltinImporter'>
```

(`find_loader() can also return `None`, which was not represented by the stubs so far. Fixed in #3341.) This is why it is necessary to narrow the type using an `assert` statement or a `cast`.

One thing that works is narrowing the loader to `importlib.machinery.SourceFileLoader` and then using `loader.path`, instead of `loader.get_filename()`, which is documented to require an argument.

**Closed by srittau** 2019-10-11 07:08 UTC
