### ISSUE TITLE
Many functions that accept Iterable should actually accept Iterable | SupportsGetItem

### ISSUE THREAD

**Issue by matangover** [python/typeshed#7814] opened 2022-05-09 21:41 UTC
Many functions in stdlib that are documented to accept an "iterable" are annotated as `Iterable[T]`. This means the arguments must have `__iter__`. However, the actual functions don't require the arguments to have `__iter__`, they also work with arguments that have only `__getitem__`. That's because internally they use `iter` (in Python) or [PySequence_Fast](https://docs.python.org/3/c-api/sequence.html#c.PySequence_Fast) (in C).

As the docs for both `iter` and the `PySequence_*` functions show, these functions support two protocols for the argument: the "iterable" protocol (`__iter__`) and the "sequence" protocol (`__getitem__`).

Example functions that have this bug right now:
```
enumerate
str.join
bytes.__new__
bytes.__join
```

For enumerate, a bug was actually filed [on the mypy repo](https://github.com/python/mypy/issues/9737) but in fact I believe this should be corrected in typeshed.

Aside: `for` loops also similarly accept "iterables" that have only `__getitem__`, but that is implemented inside type checkers themselves. For now mypy [still doesn't](https://github.com/python/mypy/issues/11695) support it properly, but Pyright does.

**Comment by JelleZijlstra** [comment] 2022-05-09 21:41
Duplicate of #7813

**Comment by matangover** [comment] 2022-05-09 21:42
Sorry, got posted twice for some reason

**Closed by JelleZijlstra** 2022-05-09 21:41 UTC
