### ISSUE TITLE
Latest types-protobuf version 4.24.0.20240106 breaks with mypy

### ISSUE THREAD

**Issue by laker-93** [python/typeshed#11263] opened 2024-01-08 11:04 UTC
When running mypy invocation under nox using the latest types-protobuf version, the following error occurs:

```
nox > mypy --explicit-package-bases python/
mypy: can't read file '.nox/mypy/lib/python3.8/site-packages//google': No such file or directory
```

This error is fixed by pinning `types-protobuf==4.24.0.4`.

**Comment by srittau** [comment] 2024-01-08 11:05
Dupe of #11254

**Closed by srittau** 2024-01-08 11:05 UTC
