### ISSUE TITLE
Ordered Dict items incompatible with tuple/argument unpacking

### ISSUE THREAD

**Issue by davidroeca** [python/typeshed#1600] opened 2017-09-11 19:19 UTC
Here's a simple example with mypy:

```python
from collections import OrderedDict

od1 = OrderedDict((
    (1, 2),
    (3, 4),
))

od2 = OrderedDict((
    (5, 6),
    (7, 8),
))

od3 = OrderedDict((
    *od1.items(),
    *od2.items(),
))
```

It can be resolved with itertools.chain and a few other ways but I'd think using items should be a valid way to instantiate an `OrderedDict`

```bash
mypy example.py
example.py:14: error: Need type annotation for variable
example.py:15: error: Argument 1 to <tuple> has incompatible type *ItemsView[int, int]; expected "Tuple[<nothing>, <nothing>]"
example.py:15: error: Argument 2 to <tuple> has incompatible type *ItemsView[int, int]; expected "Tuple[<nothing>, <nothing>]"
```
Tried on python 3.5.3 and 3.6.2, mypy 0.521

**Comment by ilevkivskyi** [comment] 2017-09-12 09:03
I am not sure this is an issue with typeshed, but with how mypy treats start types. @JukkaL what do you think?

**Comment by JukkaL** [comment] 2017-09-14 09:26
Yes, this looks like a mypy bug. Here's a repro that seems to highlight the underlying issue:

```py
from typing import Iterable, Iterator, Tuple, TypeVar

T = TypeVar('T')
S = TypeVar('S')

class C(Iterable[Tuple[T, S]]):
    def __iter__(self) -> Iterator[Tuple[T, S]]: pass

def f(*x: T) -> T: pass

x: C[str, int]
y: C[int, int]
reveal_type(f(*x))  # str, should be Tuple[str, int]
reveal_type(f(*y))  # int, should be Tuple[int, str]
```

The problem is in type inference of `*args` in calls, if I'm not mistaken.

**Comment by JukkaL** [comment] 2017-09-14 09:27
Oops this was typeshed. Closing as a mypy bug.

**Closed by JukkaL** 2017-09-14 09:27 UTC
