### ISSUE TITLE
Wrong type for `set.union`

### ISSUE THREAD

**Issue by torfsen** [python/typeshed#4756] opened 2020-11-10 16:41 UTC
Using mypy 0.790 I get a type mismatch for the following code:

```python
list_of_lists = [['x', 'y'], ['x', 'z']]
print(set().union(*list_of_lists))
```

```none
$ mypy sandbox2.py 
sandbox2.py:2: error: Argument 1 to "union" of "set" has incompatible type "*List[List[str]]"; expected "Iterable[<nothing>]"
Found 1 error in 1 file (checked 1 source file)
```

I don't really understand the type `Iterable[<nothing>]` in the error message, but IMO the code is correct from a typing POV.

**Comment by srittau** [comment] 2020-11-12 10:48
The problem is `set()`. Type checkers can't infer the type of set's type variable:

```python
reveal_type(set())  # Revealed type is 'builtins.set[<nothing>]'
```

Maybe we should add an overloaded constructor to `set.__init__()` (and other container classes) to prevent false positives:

```python
    @overload
    def __init__(self: set[Any]) -> None: ...
```

Cc @JelleZijlstra @hauntsaninja for opinions.

**Comment by hauntsaninja** [comment] 2020-11-12 19:15
I wouldn't be in favour adding that overload; seems like a really easy way to get all kinds of false negatives. mypy handles this case specially, through what it calls partial types. I think this case is more just a missing feature in mypy.

In the meantime, a good workaround is:
```
from typing import Set

Set[str]().union(*list_of_lists)
```

**Comment by Akuli** [comment] 2020-12-31 18:31
`Set[str]()` doesn't work at runtime, but e.g. `cast(Set[str], set())` works.

**Comment by srittau** [comment] 2021-01-01 13:33
Closing this per the explanations above.

**Closed by srittau** 2021-01-01 13:33 UTC
