### ISSUE TITLE
Reversible should be Iterable

### ISSUE THREAD

**Issue by crusaderky** [python/typeshed#4615] opened 2020-10-05 11:04 UTC
mypy 0.702 doesn't treat Reversible as a subclass of Iterable.

#### Workaround
Create a duck-type class that defines ``__iter__`` and ``__reversed__`` instead of relying on Reversible.

```python
from typing import Iterator, Reversible

class A:
    def __iter__(self) -> Iterator[int]:
        yield 1
        yield 2

    def __reversed__(self) -> Iterator[int]:
        yield 2
        yield 1

a: A
b: Reversible[int]


def f() -> Iterator[int]:
    yield from a
    yield from b
    yield from reversed(a)
    yield from reversed(b)
```

mypy 0.702 output:
18: error: "yield from" can't be applied to "Reversible[int]"

**Comment by JelleZijlstra** [comment] 2020-10-05 16:44
Why should it be Iterable? Reversible only says that `__reversed__` is supported, not that `__iter__` is supported.

**Comment by srittau** [comment] 2020-10-05 16:46
@JelleZijlstra In [this table](https://docs.python.org/3/library/collections.abc.html?highlight=reversible#collections-abstract-base-classes) it says that `Reversible` inherits from `Iterable`.

**Comment by JelleZijlstra** [comment] 2020-10-05 16:48
Oh, thanks! In that case I suppose https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L148 is wrong.

**Comment by hauntsaninja** [comment] 2020-10-06 19:35
Duplicate of #3470, so I guess we can close that one out too

**Closed** 2020-11-01 21:17 UTC
