### ISSUE TITLE
Type mismatch in `email.charset.Charset.get_body_encoding`

### ISSUE THREAD

**Issue by cushionbadak** [python/typeshed#10430] opened 2023-07-10 07:46 UTC
### Summary

**Modification Target**: `Charset.get_body_encoding` in `stdlib/email/charset.pyi`
**Current type hint**: `(self) -> str`
**Proposed type hint**: `(self) -> str | Callable[[Message], None]`

See the existing implementation here: [charset.pyi#L17](https://github.com/python/typeshed/blob/81b8211d0edeed0a39253e096aaab86e1699e25b/stdlib/email/charset.pyi#L17)

### Description

The method [`Charset.get_body_encoding`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/email/charset.py#L245-L264) can return [a function `encode_7or8bit`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/email/encoders.py#L47-L61) if it reaches final else-branch case.
```python
    def get_body_encoding(self):
        assert self.body_encoding != SHORTEST
        if self.body_encoding == QP:
            return 'quoted-printable'
        elif self.body_encoding == BASE64:
            return 'base64'
        else:
            return encode_7or8bit
```

Using the type hint for `encode_7or8bit`, the return type hint for `get_body_encoding` should be `str | Callable[[Message], None`.
https://github.com/python/typeshed/blob/81b8211d0edeed0a39253e096aaab86e1699e25b/stdlib/email/encoders.pyi#L7

I found this mismatch in the CPython email unit test, [`TestMiscellaneous.test_get_body_encoding_with_uppercase_charset`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/test/test_email/test_email.py#L3374-L3398), found in `test/test_email/test_email.py`. The minimized example below shows type mismatch at runtime, where the call `charset.get_body_encoding()` at the last statement returns `encode_7or8bit` function:
```python
    def test_get_body_encoding_with_uppercase_charset(self):
        eq = self.assertEqual
        # Try another one
        msg = Message()
        msg['Content-Type'] = 'text/plain; charset="US-ASCII"'
        charsets = msg.get_charsets()
        charset = Charset(charsets[0])
        eq(charset.get_body_encoding(), encoders.encode_7or8bit)
        ...
```

P.S. All CPython links refer to commit hash `0481b8...` from the current CPython 3.12 branch.

**Comment by AlexWaygood** [comment] 2023-07-10 07:48
Duplicate of #10429

**Comment by cushionbadak** [comment] 2023-07-10 08:19
@AlexWaygood 
> Duplicate of #10429

Thanks for your contribution, but I disagree with the classification of these as duplicated issues. While #10429 and #10430 might seem similar in structure, they target different methods and the reasons for the type mismatches are not identical. Therefore, in my view, these should be regarded as distinct issues. much like how issues 8615 and 8616 were jointly addressed in pull request 8617.

If the preference is still to collect similar proposals in one issue, may I suggest moving the issue report from #10430 to #10429?

**Comment by srittau** [comment] 2023-07-10 11:14
Thanks! Normally we try to avoid union return types and prefer to use `Any`, but in this case I think it's sensible to have one, since a caller needs to check the return type anyway before being able to use it. The current annotation is incomplete in any case. PR welcome!

**Closed** 2023-07-11 07:07 UTC
Labels: type-false-negative
