### ISSUE TITLE
`types-protobuf` overshadows `google-cloud` packages 

### ISSUE THREAD

**Issue by John15321** [python/typeshed#9267] opened 2022-11-24 14:32 UTC
Hi
The issue here is that the `types-protobuf` pakcage overshadows anything that `google-cloud-*` tried to export (by that I mean any google api package like `google-cloud-bigquery` or `google-cloud-storage`) which results in IDEs, language servers and all types of linters and type checkers failing even tho the code runs succesfully.

The issue is very simple to reproduce, simply install a package like `google-cloud-bigquery` and try to use it in your code.

When you open your IDE it will look something like this:
![image](https://user-images.githubusercontent.com/56229312/203807642-c67cd163-05b4-49f2-956e-b5afde77503c.png)

Tools like `mypy` or `pylint` will also not have a problem with that.

However if you install the `types-protobuf` package, which will be installed if you install `types-all` (that package is frequently installed in order for mypy to have type resolution for as many things as possible)m you will start getting errors like this (no matter the IDE):
![image](https://user-images.githubusercontent.com/56229312/203807985-ca2942f9-5083-4ab4-b936-87e019b12e84.png)

Even tho the code will run succesfully.
I am not sure if this is the fault of the `types-protobuf` package or maybe the google packages export something in a bad manner. I am simply reporting this issue, I am making a twin report in googles api repo (https://github.com/googleapis/python-bigquery/issues/1423).

**Comment by AlexWaygood** [comment] 2022-11-24 14:38
Duplicate of #5800. Should hopefully be fixed by #8360, which is just awaiting a review.

**Closed by AlexWaygood** 2022-11-24 14:38 UTC

**Comment by AlexWaygood** [comment] 2022-11-25 16:27
@John15321, can you still reproduce this with `types-protobuf==4.21.0.0`?

**Comment by John15321** [comment] 2022-12-02 10:43
> @John15321, can you still reproduce this with `types-protobuf==4.21.0.0`?

Seems to be working now! Thanks!

**Comment by AlexWaygood** [comment] 2022-12-02 10:48
Brilliant, very glad to hear it!
