### ISSUE TITLE
Missing update method on the CaseInsensitiveDict

### ISSUE THREAD

**Issue by Fokko** [python/typeshed#7632] opened 2022-04-16 07:28 UTC
We got mypy errors after the release 6 hours ago:

```
communication/slack/tasks.py:39: error: "CaseInsensitiveDict?[builtins.str]" has no attribute "update"
```

This is when we do (simplified):
```python
session = requests.Session()
session.headers.update({"Authorization": f"Bearer {access_token}"})
```

Also part of the docs: https://docs.python-requests.org/en/master/user/advanced/

I think the `CaseInsensitiveDict` should also contain the `.update()` method. Will open a PR in a second.

**Comment by AlexWaygood** [comment] 2022-04-16 08:01
Thanks! The issue isn't that `CaseInsensitiveDict` doesn't have a `.update()` method, however — it does, it inherits it from MutableMapping. The issue is that `CaseInsensitiveDict` is currently marked as a `TypeAlias` assignment following https://github.com/python/typeshed/commit/740193a8fc6499287de32e24484a3cd734c20f09#diff-bfcfcf0d08b5e5c2965394517079c5cfb2b2a11b2e27cf9d08fb07090cd9a4ceR32, meaning mypy is getting confused when you're trying to use it as a variable rather than as a type.

It's my mistake; I can send an alternative PR to fix it :)

**Comment by Fokko** [comment] 2022-04-16 08:10
Thanks for the quick response and the background info @AlexWaygood. Feel free to send an alternative PR; you're the expert here :)

**Comment by AlexWaygood** [comment] 2022-04-16 08:19
#7634 should fix it, though I haven't tested it

**Closed** 2022-04-16 08:39 UTC
