### ISSUE TITLE
Generic cached return value cannot be converted to declared value even when they are the same type

### ISSUE THREAD

**Issue by jzazo** [python/typeshed#11729] opened 2024-04-07 09:54 UTC
**Describe the bug**
I declare a generic return type, and I have a provider of that same return type, but cached. Mypy does not declare an error but Pyright raises one. If I remove the caching no error is reported.

I raised this [issue](https://github.com/microsoft/pyright/issues/6953) in pyright's repo. @erictraut stated that `cache` method does not maintain the signature of the function it's decorating. This other [issue](https://github.com/python/typeshed/issues/11280) might be related.

**Code**
```
from abc import abstractmethod
from functools import cache
from typing import Any, Generic, Protocol, TypeVar

from typing_extensions import NamedTuple

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)

class ServiceId(NamedTuple, Generic[T]):
    id: str

class Provider(Protocol[T_co]):
    @abstractmethod
    def __call__(self) -> T_co:
        ...

class Servicer:
    _d: dict[str, Any]

    @cache  # commenting this line removes the error
    def get_service(self, service_id: ServiceId[T]) -> T:
        return self._d[service_id.id]

    def get_provider(self, service_id: ServiceId[T]) -> Provider[T]:
        return lambda: self.get_service(service_id)  # Expression of type "() -> T@get_service" cannot be assigned to return type "Provider[T@get_provider]"
```

**Comment by srittau** [comment] 2024-04-07 12:53
Looks to be a duplicate of #11280.

**Closed by srittau** 2024-04-07 12:53 UTC
