### ISSUE TITLE
time.time_struct should be a 9-tuple with 2 extra properties in python3.3+

### ISSUE THREAD

**Issue by gwk** [python/typeshed#3297] opened 2019-10-03 12:56 UTC
For Python 3.3+, `time.pyi` represents `time_struct` as an 11-field NamedTuple. This is incorrect; despite the additional `tm_zone` and `tm_gmtoff` fields, it behaves as a 9-tuple: `len(gmtime()) == 9`. Note however that `gmtime().n_fields == 11`.

It appears to me that time_struct was modified to keep it's 9-tuple shape while adding two additional fields. The type stub needs to reflect this, or else mypy messes up unpacking of time_struct.

Would the correct solution be define the NamedTuple with 9 fields, plus two additional properties?

**Comment by srittau** [comment] 2019-10-03 17:11
Duplicate of #3286.

**Closed by srittau** 2019-10-03 17:11 UTC
