### ISSUE TITLE
`bytes` constructor does not permit `ctypes.Struture`

### ISSUE THREAD

**Issue by iujakchu** [python/typeshed#8922] opened 2022-10-18 11:21 UTC
```python
from ctypes import Structure

class A (Structure):
    pass


a = A()
b = bytes(a)
```
the snippet works but linter raises.

**Comment by JelleZijlstra** [comment] 2022-10-18 14:43
Duplicate of #8889 (well, at least the fix is the same).

**Closed by JelleZijlstra** 2022-10-18 14:43 UTC
